### ISSUE TITLE
Replace glog with logrus

### ISSUE THREAD

**Issue by tnachen** [mesosphere/mesos-go#114]
We received recommendation from the docker folks that logrus is a better logging library to use, and the way glog sets up flags is not ideal as it seems to clash with very common flag names.

**Comment by tnachen** [comment]
@jdef @ConnorDoyle what do you guys think? I'd like to replace glog with logrus

**Comment by haosdent** [comment]
+1

**Comment by tsenart** [comment]
What features do you need from a logging library in this particular project?

**Comment by jdef** [comment]
If we're going to replace the logging in mesos-go, I'd like to:

- support some kind of plugin design that allows people to use different
backends to avoid being tied down to a specific 3rd party lib
- maintain some level of feature parity with glog: leveled logging,
multiple levels of debug log (e.g. V(1), V(2), V(3)), log to file or
stderr, etc.


On Mon, Apr 20, 2015 at 9:11 PM, Timothy Chen <notifications@github.com>
wrote:

> @jdef <https://github.com/jdef> @ConnorDoyle
> <https://github.com/ConnorDoyle> what do you guys think? I'd like to
> replace glog with logrus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesos/mesos-go/issues/114#issuecomment-94605264>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by tsenart** [comment]
I suggest you have a look at the `log` package from the bigger `gokit` project. http://godoc.org/github.com/peterbourgon/gokit/log
https://github.com/peterbourgon/gokit/blob/master/rfc/rfc004-package-log.md

**Comment by betawaffle** [comment]
I would like to see it replaced with [clog](https://github.com/cockroachdb/clog).

**Comment by jdef** [comment]
Can a project use glog and clog at the same time without conflict?

**Comment by tsenart** [comment]
@jdef: According to your previous requirements, I'd like you to have a look at: http://godoc.org/github.com/go-kit/kit/log

**Comment by tsenart** [comment]
Replaced by #170
