### ISSUE TITLE
update protobuf API to v0.22+

### ISSUE THREAD

**Issue by jdef** [mesosphere/mesos-go#121]

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/256

**Comment by sargun** [comment]
It would be lovely to get access to the Mesos shared log as part of this as well. Is that a TODO?

**Comment by jdef** [comment]
Agreed, a state abstraction would be most welcome. See #139.

**Comment by tsenart** [comment]
Replaced by #167
