### ISSUE TITLE
tagged releases corresponding to compatible mesos versions

### ISSUE THREAD

**Issue by spacejam** [mesosphere/mesos-go#165]
Problem:  I'm running mesos version X.  What git SHA should I be using?

**Comment by spacejam** [comment]
Initially, I'd like to see a tag for:
0.22.0
0.23.0 (after https://github.com/mesos/mesos-go/pull/159 is merged in and more testing is performed)
new versions after they have been properly tested

**Comment by tsenart** [comment]
Merged with #166.
