### ISSUE TITLE
UPID - explicitly validate string in Parse()

### ISSUE THREAD

**Issue by vladimirvivien** [mesosphere/mesos-go#22]
Use regexp `[A-Za-z0-9_\-]+@[A-Za-z0-9_\-]+:[0-9]+` to validate parsed string.

**Comment by jdef** [comment]
Probably want to include dots and avoid leading zeroes for ports:

`[A-Za-z0-9_\-]+@[A-Za-z0-9_\-\.]+:[1-9][0-9]*`

**Comment by tsenart** [comment]
Duplicate of  #150
